import os
import time
from time import sleep
from selenium import webdriver
from py._xmlgen import html
import pytest
from selenium.webdriver.chrome.webdriver import WebDriver
driver:webdriver=webdriver.Chrome()
def test_setup():
    global driver
    driver.implicitly_wait(10)
    driver.maximize_window()
def test_selectjob():
    driver.get("https://www.mondaymorning.in")
    time.sleep(2)
    driver.find_element_by_xpath("(//LI[@class='nav-item '])[2]").click()
    time.sleep(2)
    driver.find_element_by_xpath("(//INPUT[@id='myInput'])").send_keys("sales executive")
    time.sleep(1)
    driver.find_element_by_xpath("(//I[@class='fa fa-search '])").click()
    time.sleep(1)
    driver.find_element_by_xpath("(//A[@class='btn btn-fb btn-rounded float-right  btn-sm waves-effect waves-light'])[2]").click()
    time.sleep(2)
    driver.find_element_by_xpath("(//I[@class='fa fa-check'])[' Apply']").click()
    time.sleep(2)
def test_signup():
    driver.find_element_by_xpath("(//A[@id='checkInToggleSystem'])['Sign Up']").click()
    time.sleep(2)
    driver.find_element_by_xpath("(//I[@class='fas fa-user-circle'])['Sign Up']").click()
    sleep(1)
    driver.find_element_by_id("name").send_keys("Rakesh")
    sleep(1)
    driver.find_element_by_id("lastname").send_keys("Patra")
    sleep(1)
    driver.find_element_by_name("user_email").send_keys("rakesh_patra+1052@mondaymorning.in")
    sleep(1)
    driver.find_element_by_id("password").send_keys("1234")
    sleep(1)
    driver.save_screenshot("Screenshoot1.png")
    driver.find_element_by_id("signip-submit").click()
    sleep(3)
    driver.find_element_by_xpath("(//I[@class='fa fa-check-square-o'])['Apply']").click()
    sleep(2)
    print("A New user is registered.")
def test_emailverification():
    driver.find_element_by_xpath("(//BUTTON[@type='button'])[3]").click()
    time.sleep(5)
    driver.execute_script("window.open('https://www.google.com','new window')")  ####Open a new tab
    time.sleep(3)
    driver.execute_script("window.alert('Please verify your email !');")
    time.sleep(1)
    alert = driver.switch_to_alert()
    time.sleep(1)
    alert.accept()
    time.sleep(30)
    driver.switch_to.window(driver.window_handles[0])
    time.sleep(2)
    driver.refresh()
    driver.find_element_by_xpath("(//I[@class='fa fa-check-square-o'])['Apply']").click()
    time.sleep(2)
def test_JAF_question():
    global driver
    x = driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])['Yes'][1]").click()
    time.sleep(2)
    if not x == ("(//LABEL[@class='form-check-label'])['Yes'][1]"):
        time.sleep(2)
        while True:
            try:
                x = driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])[2]").click()
                time.sleep(2)
            except:
                driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])['Yes'][1]").click()
            else:
                print(" Whopp's something went wrong ! ")
            finally:
                driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])[5]").click()
                time.sleep(2)
                driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])[3]").click()
                time.sleep(2)
                driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])[9]").click()
                time.sleep(2)
                driver.find_element_by_xpath("(//textarea[@id='testcons-185'])").send_keys("Noida")
                time.sleep(2)
                driver.find_element_by_xpath("(//BUTTON[@id='nextBtn'])['Save & Continue']").click()
                time.sleep(2)
def test_Instruction():
    driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])").click()
    sleep(2)
    driver.find_element_by_xpath("(//I[@class='fa fa-angle-double-right'])").click()
def test_starttest():
    print("Test should start ASAP! ")
    driver.find_element_by_xpath("(//DIV[@class='mcq-question'])[1]").click()
    sleep(1)
    driver.find_element_by_xpath("(//BUTTON[@id='question-next'])['Save & Continue']").click()
    sleep(1)
    driver.find_element_by_xpath("(//DIV[@class='mcq-question'])[5]").click()
    sleep(2)
    driver.find_element_by_xpath("(//BUTTON[@id='question-next'])['Save & Continue']").click()
    sleep(1)
    driver.find_element_by_xpath("(//LI[@class='button_example'])['Last']").click()
    sleep(1)
    driver.find_element_by_xpath("(//DIV[@class='mcq-question'])[57]").click()
    sleep(1)
    driver.find_element_by_xpath("(//BUTTON[@class='btn  btn-primary-custom'])['Finish']").click()
    sleep(1)
    driver.find_element_by_xpath("(//BUTTON[@id='confirmsucess'])['Ok']").click()
    sleep(2)
    driver.find_element_by_xpath("(//A[@class='skip-feedback tl-center btn btn-success'])['Continue']").click()
    sleep(2)
    driver.find_element_by_xpath("(//A[@type='button'])['Insights'][1]").click()
    sleep(2)
    print("Test is completed and Processed.")
def test_logout():
    driver.find_element_by_xpath("(//IMG[@id='my-profile'])[1]").click()
    sleep(2)
    driver.find_element_by_xpath("(//I[@class='fa-fw fa fa-power-off '])[1]").click()
    sleep(2)
    print("New User has logged out")
    while True:
        try:
            driver.find_element_by_name("user_login").send_keys("rakesh_patra+1052@mondaymorning.in")
            sleep(1)
            driver.find_element_by_name("user_pwd").send_keys("1234")
            sleep(1)
            driver.find_element_by_xpath("(//INPUT[@class='log-btn'])[1]").click()
            sleep(1)
        except:
            print("Whopp's")
        else:
            driver.execute_script("window.alert('Apply for the job');")  #####Proceeding for JAF Process
            alert = driver.switch_to_alert()
            sleep(2)
            alert.accept()
            driver.find_element_by_xpath("//A[@id='navbarDropdownMenuLink-555'][text()='Jobs']").click()
            sleep(1)
            driver.find_element_by_xpath("//A[@class='dropdown-item waves-effect waves-light']").click()
            sleep(2)
            driver.save_screenshot("Screenshoot1.png")
            driver.find_element_by_xpath("(//A[@class='btn btn-fb btn-rounded float-right  btn-sm waves-effect waves-light'])[text()='Apply'][1]").click()
            sleep(2)
            driver.find_element_by_xpath("(//I[@class='fa fa-check-square-o'])[' Apply']").click()
            sleep(2)
            # driver.find_element_by_xpath("(//BUTTON[@type='button'])[3]").click()
            # sleep(2)
            driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])").click()
            sleep(2)
            driver.find_element_by_xpath("(//BUTTON[@type='button'])['Start Test'][1]").click()
            sleep(2)
            print("PROCEED FOR THE TEST.")
def test_onboard():
    driver.find_element_by_xpath("//BUTTON[@class='btn btn-default mw-btn-300  my-default-btn-set yesBtn'][text()='Next']").click()
    sleep(3)
    driver.find_element_by_xpath("//LABEL[@for='radior_1_5'][text()='have a die hard attitude']").click()
    sleep(3)
    driver.find_element_by_xpath("//button[@class='btn btn-default mw-btn-300  my-default-btn-set nextBtn'][text()='Next']").click()
    sleep(3)
    driver.find_element_by_xpath("//label[@for='radior_2_1'][text()='working']").click()
    sleep(1)
    driver.find_element_by_xpath("(//BUTTON[@class='btn btn-default mw-btn-300  my-default-btn-set nextBtn'][text()='Next'][text()='Next'])[2]").click()
    sleep(1)
    driver.find_element_by_xpath("//label[@for='radior_3_2'][text()='Frontline Manager']").click()
    sleep(1)
    driver.find_element_by_xpath("(//BUTTON[@class='btn btn-default mw-btn-300  my-default-btn-set nextBtn'][text()='Next'][text()='Next'])[3]").click()
    sleep(1)
    driver.find_element_by_xpath("//*[@id='select2-list_4-container']/span").click()
    sleep(3)
    # obj=span (self.driver.find_element_by_class_name('select2-selection__rendered'))

    driver.find_element_by_xpath("//INPUT[@class='select2-search__field']").send_keys("Energy")
    sleep(2)
    driver.find_element_by_xpath("(//LI[@title='Energy'])['Energy']").click()
    sleep(2)
    driver.find_element_by_xpath("(//BUTTON[@class='btn btn-default mw-btn-300  my-default-btn-set nextBtn'])[4]").click()
    sleep(3)
    driver.find_element_by_xpath("(//SPAN[@id='select2-list_5-container'])/SPAN").click()
    sleep(2)
    driver.find_element_by_xpath("(//INPUT[@type='search'])").send_keys("Technology/IT")
    sleep(2)
    driver.find_element_by_xpath("(//LI[@title='Technology/IT'])").click()
    driver.find_element_by_xpath("(//BUTTON[@class='btn btn-default mw-btn-300  my-default-btn-set nextBtn'])[5]").click()
    sleep(2)
    driver.find_element_by_xpath("(//LABEL[@for='radior_6_1'])['radior_6_1']").click()
    sleep(1)
    driver.find_element_by_xpath("(//BUTTON[@class='btn btn-default mw-btn-300  my-default-btn-set nextBtn'])[6]").click()
    sleep(1)
    driver.find_element_by_xpath("(//BUTTON[@class='btn btn-default mw-btn-300  my-default-btn-set nextBtn'])[7]").click()
    sleep(1)

    # driver.find_element_by_xpath("(//A[@class='skipBtn btn btn-default   my-default-btn-set-2'])['Skip'][1]").click()
    print("User is onboarded")
    sleep(5)
def test_Applyjob():
    driver.execute_script("window.alert('Apply for the job');")  #####Proceeding for JAF Process
    alert = driver.switch_to_alert()
    sleep(2)
    alert.accept()
    driver.find_element_by_xpath("//A[@id='navbarDropdownMenuLink-555'][text()='Jobs']").click()
    sleep(1)
    driver.find_element_by_xpath("//A[@class='dropdown-item waves-effect waves-light']").click()
    sleep(2)
    driver.save_screenshot("Screenshoot1.png")
    driver.find_element_by_xpath("(//A[@class='btn btn-fb btn-rounded float-right  btn-sm waves-effect waves-light'])[text()='Apply'][7]").click()
    sleep(2)
    driver.find_element_by_xpath("(//I[@class='fa fa-check-square-o'])[' Apply']").click()
    sleep(2)
    driver.find_element_by_xpath("(//BUTTON[@type='button'])[3]").click()
    sleep(3)
    print("One job has been Processed")
# def test_logout():
#     driver.find_element_by_xpath("(//IMG[@id='my-profile'])[1]").click()
#     sleep(2)
#     driver.find_element_by_xpath("(//I[@class='fa-fw fa fa-power-off '])[1]").click()
#     sleep(2)
#     print("New User has logged out")
#     while True:
#         try:
#             driver.find_element_by_name("user_login").send_keys("rakesh_patra+1013@mondaymorning.in")
#             sleep(1)
#             driver.find_element_by_name("user_pwd").send_keys("1234")
#             sleep(1)
#             driver.find_element_by_xpath("(//INPUT[@class='log-btn'])[1]").click()
#             sleep(1)
#         except:
#             driver.execute_script("window.alert('Apply for the job');")  #####Proceeding for JAF Process
#             alert = driver.switch_to_alert()
#             sleep(2)
#             alert.accept()
#             driver.find_element_by_xpath("//A[@id='navbarDropdownMenuLink-555'][text()='Jobs']").click()
#             sleep(1)
#             driver.find_element_by_xpath("//A[@class='dropdown-item waves-effect waves-light']").click()
#             sleep(2)
#             driver.save_screenshot("Screenshoot1.png")
#             driver.find_element_by_xpath("(//A[@class='btn btn-fb btn-rounded float-right  btn-sm waves-effect waves-light'])[text()='Apply'][1]").click()
#             sleep(2)
#             driver.find_element_by_xpath("(//I[@class='fa fa-check-square-o'])[' Apply']").click()
#             sleep(2)
#             # driver.find_element_by_xpath("(//BUTTON[@type='button'])[3]").click()
#             # sleep(2)
#             driver.find_element_by_xpath("(//LABEL[@class='form-check-label'])").click()
#             sleep(2)
#             driver.find_element_by_xpath("(//BUTTON[@type='button'])['Start Test'][1]").click()
#             sleep(2)
#             print("PROCEED FOR THE TEST.")
# def test_starttest():
#     print("Test should start ASAP! ")
#     driver.find_element_by_xpath("(//DIV[@class='mcq-question'])[1]").click()
#     sleep(1)
#     driver.find_element_by_xpath("(//BUTTON[@id='question-next'])['Save & Continue']").click()
#     sleep(1)
#     driver.find_element_by_xpath("(//DIV[@class='mcq-question'])[5]").click()
#     sleep(2)
#     driver.find_element_by_xpath("(//BUTTON[@id='question-next'])['Save & Continue']").click()
#     sleep(1)
#     driver.find_element_by_xpath("(//LI[@class='button_example'])['Last']").click()
#     sleep(1)
#     driver.find_element_by_xpath("(//DIV[@class='mcq-question'])[57]").click()
#     sleep(1)
#     driver.find_element_by_xpath("(//BUTTON[@class='btn  btn-primary-custom'])['Finish']").click()
#     sleep(1)
#     driver.find_element_by_xpath("(//BUTTON[@id='confirmsucess'])['Ok']").click()
#     sleep(2)
#     driver.find_element_by_xpath("(//A[@class='skip-feedback tl-center btn btn-success'])['Continue']").click()
#     sleep(2)
#     driver.find_element_by_xpath("(//A[@type='button'])['Insights'][1]").click()
#     sleep(2)
#     print("Test is completed and Processed.")

def test_teardown():
    driver.close()
    print("Test Completed")
