# Generated by Django 3.0 on 2020-02-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200215_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
