# Generated by Django 3.0 on 2020-02-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200215_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
