# Generated by Django 3.0 on 2020-02-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200221_0104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='events',
        ),
    ]
