# Generated by Django 3.0 on 2020-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200221_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='number',
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
