# Generated by Django 3.0 on 2020-02-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200221_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_category',
            field=models.CharField(choices=[('Birthday event', 'Birthday event'), ('Office event', 'Office event'), ('Team event', 'Team event'), ('House event', 'House event')], max_length=200, null=True),
        ),
    ]
