# Generated by Django 3.0 on 2020-02-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Food & Beverage', 'Food & Beverage'), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200, null=True),
        ),
    ]
